### ISSUE TITLE
Parentheses after Directive (Expected Behaviour)

### ISSUE THREAD

**Issue by Jubeki** [ryangjchandler/prettier-plugin-blade#24]
It seems like in the Laravel Docs there is sometimes a space between the directive and the parantheses.

The directives are:
https://laravel.com/docs/master/blade#loops
- `@for`
- `@foreach`
- `@forelse`
- `@while`

https://laravel.com/docs/master/blade#if-statements
- `@if` 
- `@elseif`
- `@unless`

But some others don't put a space between the directive and the parantheses:
https://laravel.com/docs/master/blade#authentication-directives
- `@auth('admin')`

https://laravel.com/docs/master/blade#switch-statements
- `@switch`
- `@case`

This is how a test would need to be changed:

```blade
@if (count($records) === 1)
    I have one record!
@elseif (count($records) >  1)I have multiple records!
@else
    I don't have any records!@endif

----
{{-- Not Following the Laravel Docs --}}
@if(count($records) === 1)
    I have one record!
@elseif(count($records) > 1)
    I have multiple records!
@else
    I don't have any records!
@endif

{{-- Following the Laravel Docs --}}
@if (count($records) === 1)
    I have one record!
@elseif (count($records) > 1)
    I have multiple records!
@else
    I don't have any records!
@endif
```

What is the expected behaviour of the prettier plugin?
In my opinion there should be no space between the directive and the parantheses, but this doesn't align with the docs.

**Comment by ryangjchandler** [comment]
I personally don't use spaces - some people do. We'll likely use a config option for this though.

**Comment by olivernybroe** [comment]
I think we should go with no spaces and then let's keep this issue open for making it configurable 👍

**Comment by olivernybroe** [comment]
As we have a separate issue for configuration which already mentions this, we are going to close this, for cleaning up the issue board 👍 #26
