### ISSUE TITLE
Separate out fixture tests

### ISSUE THREAD

**Issue by benjam-es** [ryangjchandler/prettier-plugin-blade#27]
Is it worth separating the fixture tests out into different test files? Just wondering if that will simplify adding new tests and code so we're not running all fixture tests each time.

**Comment by ryangjchandler** [comment]
@benjam-es The fixtures approach makes it a lot simpler to actually write the tests - we'll keep it as it is for now. I'm currently working on a small CLI script that you'll be able to run to see the output for a particular files. That should make testing a lot simpler.
