### ISSUE TITLE
[Bug] Each save adds additional blank lines.

### ISSUE THREAD

**Issue by mikebronner** [ryangjchandler/prettier-plugin-blade#32]
Given the following snippet:

```blade
<div>
    <div>
        @foreach
            <p>text</p>
        @endforeach
    </div>
</div>
```

After the first save, the code looks like this:
```blade
<div>
    <div>
        @foreach

        <p>text</p>

@endforeach
    </div>
</div>
```

After running prettier a second time, it looks like this, and doesn't change after subsequent runs:
```blade
<div>
    <div>
        @foreach


        <p>text</p>


@endforeach
    </div>
</div>
```

I see two issues here:

1. The closing tag is moved out of its correct indentation.
2. Empty lines are being added. If it was intentional to add empty lines, it should probably only add one, and not two.

**Comment by ryangjchandler** [comment]
@mikebronner We're currently implementing a new lexer & formatting process that should 🤞 solve this!

**Comment by claytonrcarter** [comment]
I believe this is fixed on `main`.
