### ISSUE TITLE
bracketSameLine setting not being obeyed?

### ISSUE THREAD

**Issue by yabdab** [ryangjchandler/prettier-plugin-blade#41]
In my prettier.config.js file I have the following ...

`module.exports = {
	tailwindConfig: "./tailwind.config.js",
	bracketSameLine: true,
};`

The bracketSameLine setting is obeyed in html and js files, but not blade.

Is this a bug or am I doing something wrong?

Thanks.

**Comment by claytonrcarter** [comment]
Yes, I believe that there's currently an issue w/ passing user defined options through to the parsers. I noticed it b/c I have `singleQuote: true` in my config and it wasn't be passed through to either of the parsers. I have a fix in the works, but it's a little iffy.

**Comment by yabdab** [comment]
This is not fixed for `bracketSameLine`. Still does not work.

**Comment by yabdab** [comment]
I guess I am just running wrong build. I downloaded and built the plugin, but no change to before  ¯\_(ツ)_/¯ 

May just need to wait until the changes are built into the dist on github?

**Comment by claytonrcarter** [comment]
Oh! The other thing to consider is that your app might be using long running prettier process, and that process may have "cached" the plugin from it last started. You might try restarting you app after rebuilding to see if that helps. If not, then I'm *definitely* out of ideas. Good luck.
