### ISSUE TITLE
Empty directives cause destructive formatting

### ISSUE THREAD

**Issue by claytonrcarter** [ryangjchandler/prettier-plugin-blade#44]
**Input:**

```
@if($foo)
@endif
```

**Output:**

```
 @endif
```

**Expected:**

```
@if($foo)
@endif

// or 

@if($foo) @endif
```

Needless to say, this is undesirable. 😄 

I think that this has to do w/ this pattern: ``\n?.*<\\/if-open-${uuid}>` b/c the input is transformed into this:
```
<if-open-2> <div x-delete-x></div>
 </if-open-2>  <if-close-2 />
```
which is then formatted into this:
```
<if-open-2> <div x-delete-x></div> </if-open-2> <if-close-2 />
```
So that pattern is too aggressive and is gobbling up everything up to the start of the line.

**Comment by olivernybroe** [comment]
Haha yeah, I have had multiple issues like this one. 

However this actually raises a funny one, if the if statement is empty, should we just delete the if statement? 👀

**Comment by hexsprite** [comment]
probably, but what if the expression has side effects?

**Comment by claytonrcarter** [comment]
For my part, I would vote "no" to removing it. At least in PHP/JS, I often start w/ something like `if(){}`, save to format, fill in my condition, save again to clean it up, then start working on the statement. I think I would find it bothersome if were removed, but that's just me. 😄

**Comment by olivernybroe** [comment]
@claytonrcarter totally agree. It was more to point it out. 
This is also prettier. It's a code formatting tool, it's not meant to find errors in your code, we got phpstan for that
